version: "3.9"
services:
  api:
    build:
      context: .
      target: runtime
    container_name: whatsapp-max-api
    environment:
      NODE_ENV: production
      PORT: ${PORT:-3000}
      SESSIONS_DIR: /app/sessions
      API_KEY: ${API_KEY}
      HEADLESS: ${HEADLESS:-true}
      CHROME_EXECUTABLE_PATH: /usr/bin/chromium
      CHROME_EXTRA_ARGS: ${CHROME_EXTRA_ARGS:---no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-gpu}
      WEBHOOK_TIMEOUT_MS: ${WEBHOOK_TIMEOUT_MS:-6000}
      WEBHOOK_MAX_RETRIES: ${WEBHOOK_MAX_RETRIES:-6}
      MAX_CONCURRENT_SESSIONS: ${MAX_CONCURRENT_SESSIONS:-0}
      BOOTSTRAP_READY_TIMEOUT_MS: ${BOOTSTRAP_READY_TIMEOUT_MS:-60000}
      DESTROY_MAX_RETRIES: ${DESTROY_MAX_RETRIES:-5}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - whatsapp-max-sessions:/app/sessions
    restart: unless-stopped
    stop_signal: SIGTERM
    stop_grace_period: 40s

volumes:
  whatsapp-max-sessions:
    external: true
